baseURL = "https://github.com/WanHsuanChiang/wanhsuanchiang.github.io/"
languageCode = "en-us"
title = "Angela Chiang's Portfolio"
theme = "PaperMod"

[param]
env = "production"
title = "Angela Chiang's Portfolio"
description = "Know more about Angela"
DateFormat = "January 2, 2006"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Know more about Angela"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/wanhsuanchiang/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/WanHsuanChiang"