baseURL = 'https://wanhsuanchiang.github.io/'
languageCode = 'en-us'
title = 'Angela Chiang's Portfolio'
theme = "PaperMod"

[param]
env = 'production'
title = 'Angela Chiang's Portfolio'
descrption = 'Know more about Angela'
DateFormat = "January 2, 2006"