baseURL = "https://wanhsuanchiang.github.io/"
languageCode = "en-us"
title = "Angela Chiang's Portfolio"
theme = "PaperMod"



[params]
  [params.profileMode]
    enabled = true
    title = "Angela Chiang's Portfolio"
    subtitle = "Know more about Angela"
    imageUrl = "/imgs/notion-avatar-1701081974658.svg" # optional
    imageTitle = "My Avatar" # optional
    imageWidth = 150 # custom size
    imageHeight = 150 # custom size
    [[params.profileMode.buttons]]
      name = "Portfolio"
      url = "/portfolio"
    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/blog"
    

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/wanhsuanchiang/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/WanHsuanChiang"
  
  [[params.socialIcons]]
    name = "email"
    url = "mailto:ezgtt324@gmail.com"